service: pukara-api

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    packager: 'yarn'
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
